server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
      discovery:
        locator:
          enabled: true
      routes:
          # 商品微服务
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
          # 购物车微服务
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/*/cart/**
          # 用户微服务
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
          # 订单微服务
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
  redis:
    host: 192.168.200.128
    port: 6379